apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-node-labeller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-node-labeller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceName:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-node-labeller
subjects:
- kind: ServiceAccount
  name: kubevirt-node-labeller
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-cpu-plugin-configmap
data:
  cpu-plugin-configmap.yaml: |- 
    obsoleteCPUs:
      - "486"
      - "pentium"
      - "pentium2"
      - "pentium3"
      - "pentiumpro"
      - "coreduo"
      - "n270"
      - "core2duo"
      - "Conroe"
      - "athlon"
      - "phenom"
      - "kvm32"
    minCPU: "Penryn"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubevirt-node-labeller
  name: kubevirt-node-labeller
spec:
  selector:
    matchLabels:
      app: kubevirt-node-labeller
  template:
    metadata:
      labels:
        app: kubevirt-node-labeller
    spec:
      serviceAccount: kubevirt-node-labeller
      containers:
      - name: kubevirt-node-labeller-sleeper
        image: quay.io/ksimon/kubevirt-node-labeller:v0.0.5
        command: ["sleep"]
        args: ["infinity"]
      initContainers:

        - image: quay.io/fromani/kvm-info-nfd-plugin:v0.4.0
          command: ["/bin/sh","-c"]
          args: ["cp /usr/bin/kvm-caps-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/;"]
          imagePullPolicy: Always
          name: kvm-info-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
  
        - image: quay.io/ksimon/kubevirt-cpu-nfd-plugin:v0.0.4
          command: ["/bin/sh","-c"]
          args: ["cp /plugin/dest/kubevirt-cpu-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/; cp /config/cpu-plugin-configmap.yaml /etc/kubernetes/node-feature-discovery/source.d/cpu-plugin-configmap.yaml;"]
          imagePullPolicy: Always
          name: kubevirt-cpu-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
            - mountPath: /config
              name: cpu-config

        - image: kubevirt/libvirt:5.0.0
          command: ["/bin/sh","-c"]
          args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities --machine q35 --arch x86_64 --virttype kvm > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml; cp -r /usr/share/libvirt/cpu_map /etc/kubernetes/node-feature-discovery/source.d/"]
          imagePullPolicy: Always
          name: libvirt
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: quay.io/ksimon/kubevirt-node-labeller:v0.0.5
          name: kubevirt-node-labeller
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"

      volumes:
        - name: nfd-source
          emptyDir: {}
        - name: cpu-config
          configMap:
            name: kubevirt-cpu-plugin-configmap
